language: node_js
node_js:
  - '10'

install:
  - npm install -g firebase-tools

script:
  - yarn
  - yarn build

# safelist
branches:
  only:
    - master
    - develop
jobs:
  include:
    - stage: deploy
      script:
        - yarn build
        - bash scripts/deploy.sh
