language: node_js
node_js:
  - "10"

script:
  - yarn
  - yarn build

install:
  - npm install -g firebase-tools

# safelist
branches:
  only:
    - master
    - develop
jobs:
  include:
    - stage: deploy
      script: bash scripts/deploy.sh
